name: FishermenNeverLie
favicon: null
layout_spectrum: 0.8191697620786726
typography_spectrum: 0.7424806591589004
title: Fishermen never Lie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5182370687834918
  lightness: 0.9015254445839673
  saturation: 0.6153477157931775
  rhythmicContrast: 0.3808643617667258
purpose: []
